name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Change this to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        # if: steps.cache.outputs.cache-hit != 'true' # 如果没有缓存的话
        run: pnpm i # 安装依赖

      - name: Build
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
